<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>fiveyears3</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Scripts\Dados\JSONS\Dia_02\Noticias.json" />
    <Content Include="scripts\dados\jsons\dia_01\Noticias.json" />
    <Content Include="scripts\dados\jsons\rotinas_semanais.json" />
    <Content Include="scripts\globais\gerenciadordeflagsnarrativas\QuandoSaoAtivadas.json" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scripts\Dados\JSONS\Dia_01\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="coisas_feitas.md" />
    <None Include="gdd.md" />
  </ItemGroup>
</Project>