using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flags;

public enum FlagNarrativa
{

    AntenaQuebrada_01,
    RevoltaPopularIniciandoGovernoBateAPorta
}

public enum FlagsCondicionais
{
    //FLAGS DE MUSICA TOCADA
    PRIMEIRA_MUSICA_TOCADA,
    SEGUNDA_MUSICA_TOCADA,
    TERCEIRA_MUSICA_TOCADA,
    QUARTA_MUSICA_TOCADA,
    QUINTA_MUSICA_TOCADA,
    SEXTA_MUSICA_TOCADA,
    SETIMA_MUSICA_TOCADA,
    OITAVA_MUSICA_TOCADA,
    NONA_MUSICA_TOCADA,
    DECIMA_MUSICA_TOCADA,
    DECIMA_PRIMEIRA_MUSICA_TOCADA,
    DECIMA_SEGUNDA_MUSICA_TOCADA,
    DECIMA_TERCEIRA_MUSICA_TOCADA,
    DECIMA_QUARTA_MUSICA_TOCADA,
    DECIMA_QUINTA_MUSICA_TOCADA,
    DECIMA_SEXTA_MUSICA_TOCADA,
    DECIMA_SETIMA_MUSICA_TOCADA,
    DECIMA_OITAVA_MUSICA_TOCADA,
    DECIMA_NONA_MUSICA_TOCADA,
    VIGESIMA_MUSICA_TOCADA,
    VIGESIMA_PRIMEIRA_MUSICA_TOCADA,
    VIGESIMA_SEGUNDA_MUSICA_TOCADA,
    VIGESIMA_TERCEIRA_MUSICA_TOCADA,
    VIGESIMA_QUARTA_MUSICA_TOCADA,
    VIGESIMA_QUINTA_MUSICA_TOCADA,
    VIGESIMA_SEXTA_MUSICA_TOCADA,
    VIGESIMA_SETIMA_MUSICA_TOCADA,
    VIGESIMA_OITAVA_MUSICA_TOCADA,
    VIGESIMA_NONA_MUSICA_TOCADA,
    TRIGESIMA_MUSICA_TOCADA,

    //FLAGS DE MUSICAS DISPARADAS
    PRIMEIRA_MUSICA_DISPARADA_RADIO,
    SEGUNDA_MUSICA_DISPARADA_RADIO,
    TERCEIRA_MUSICA_DISPARADA_RADIO,
    QUARTA_MUSICA_DISPARADA_RADIO,
    QUINTA_MUSICA_DISPARADA_RADIO,
    SEXTA_MUSICA_DISPARADA_RADIO,
    SETIMA_MUSICA_DISPARADA_RADIO,
    OITAVA_MUSICA_DISPARADA_RADIO,
    NONA_MUSICA_DISPARADA_RADIO,
    DECIMA_MUSICA_DISPARADA_RADIO,
    DECIMA_PRIMEIRA_MUSICA_DISPARADA_RADIO,
    DECIMA_SEGUNDA_MUSICA_DISPARADA_RADIO,
    DECIMA_TERCEIRA_MUSICA_DISPARADA_RADIO,
    DECIMA_QUARTA_MUSICA_DISPARADA_RADIO,
    DECIMA_QUINTA_MUSICA_DISPARADA_RADIO,
    DECIMA_SEXTA_MUSICA_DISPARADA_RADIO,
    DECIMA_SETIMA_MUSICA_DISPARADA_RADIO,
    DECIMA_OITAVA_MUSICA_DISPARADA_RADIO,
    DECIMA_NONA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_PRIMEIRA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_SEGUNDA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_TERCEIRA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_QUARTA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_QUINTA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_SEXTA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_SETIMA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_OITAVA_MUSICA_DISPARADA_RADIO,
    VIGESIMA_NONA_MUSICA_DISPARADA_RADIO,
    TRIGESIMA_MUSICA_DISPARADA_RADIO,

    // Flags de narrativa
    REVOLTA_POPULAR_INICIANDO,


    // Flags de dias
    DIA_1_INICIADO,
    DIA_2_INICIADO

}